import { useState, useEffect } from 'react';

const translations = {
  'Português (BR)': {
    // Sidebar
    home: 'Início',
    search: 'Buscar',
    profile: 'Meu Perfil',
    settings: 'Configurações',
    // Feed
    feedTitle: 'INÍCIO',
    whatThinking: 'No que você está pensando?',
    publish: 'Publicar',
    comments: 'comentários',
    reposts: 'reposts',
    likes: 'curtidas',
    noPosts: 'Nenhuma publicação por aqui ainda.',
    noComments: 'Nenhum comentário ainda. Seja o primeiro!',
    commentPlaceholder: 'Escreva um comentário...',
    commentBtn: 'Comentar',
    loading: 'Carregando...',
    // Mural / Buscar
    searchTitle: 'BUSCAR',
    muralTitle: 'Mural Acadêmico',
    noAnnouncements: 'Nenhum aviso encontrado.',
    createAnnouncement: 'Criar Aviso',
    // Perfil
    editProfile: 'Editar Perfil',
    followers: 'seguidores',
    following: 'seguindo',
    teacher: '🎓 Docente',
    student: '📖 Discente',
    postsTab: 'Posts',
    repostsTab: 'Reposts',
    follow: 'Seguir',
    unfollow: 'Seguindo',
    // Mensagens
    messagesTitle: 'MENSAGENS',
    searchContacts: 'Buscar contatos...',
    contactsAvailable: 'CONTACTOS DISPONÍVEIS',
    noContacts: 'Nenhum contato encontrado.',
    connected: 'Conectado',
    chatPlaceholder: 'Conversar com',
    voiceMsg: 'Mensagem de voz',
    calling: 'Chamando...',
    callConnected: 'Conectado',
    callProtected: 'Chamada Protegida',
    callEncrypted: 'Criptografada de ponta a ponta',
    micMute: 'Desativar Microfone',
    micUnmute: 'Ativar Microfone',
    camMute: 'Desativar Câmera',
    camUnmute: 'Ativar Câmera',
    endCall: 'Desligar Chamada',
    // Configuracoes
    settingsTitle: 'CONFIGURAÇÕES',
    security: 'Segurança',
    changePassword: 'Alterar senha',
    twoFactor: 'Verificação em duas etapas (2FA)',
    recoveryEmail: 'E-mail de recuperação',
    privacy: 'Privacidade',
    privateAccount: 'Conta privada',
    hideActivity: 'Ocultar minha atividade',
    whoMention: 'Quem pode me mencionar',
    all: 'Todos',
    onlyFollowers: 'Apenas Seguidores',
    nobody: 'Ninguém',
    nightMode: 'Modo Noturno',
    accessibility: 'Acessibilidade & Interface',
    highContrast: 'Aumentar contraste de cores',
    textSize: 'Tamanho do texto global',
    small: 'pequena',
    medium: 'média',
    large: 'grande',
    systemLanguage: 'Idioma do sistema',
    logout: 'sair da conta',
  },
  'English': {
    home: 'Home',
    search: 'Search',
    profile: 'My Profile',
    settings: 'Settings',
    feedTitle: 'HOME',
    whatThinking: "What's on your mind?",
    publish: 'Publish',
    comments: 'comments',
    reposts: 'reposts',
    likes: 'likes',
    noPosts: 'No posts around here yet.',
    noComments: 'No comments yet. Be the first!',
    commentPlaceholder: 'Write a comment...',
    commentBtn: 'Comment',
    loading: 'Loading...',
    searchTitle: 'SEARCH',
    muralTitle: 'Academic Wall',
    noAnnouncements: 'No announcements found.',
    createAnnouncement: 'Create Announcement',
    editProfile: 'Edit Profile',
    followers: 'followers',
    following: 'following',
    teacher: '🎓 Faculty',
    student: '📖 Student',
    postsTab: 'Posts',
    repostsTab: 'Reposts',
    follow: 'Follow',
    unfollow: 'Following',
    messagesTitle: 'MESSAGES',
    searchContacts: 'Search contacts...',
    contactsAvailable: 'AVAILABLE CONTACTS',
    noContacts: 'No contacts found.',
    connected: 'Connected',
    chatPlaceholder: 'Chat with',
    voiceMsg: 'Voice message',
    calling: 'Calling...',
    callConnected: 'Connected',
    callProtected: 'Secure Call',
    callEncrypted: 'End-to-end encrypted',
    micMute: 'Mute Microphone',
    micUnmute: 'Unmute Microphone',
    camMute: 'Mute Camera',
    camUnmute: 'Unmute Camera',
    endCall: 'End Call',
    settingsTitle: 'SETTINGS',
    security: 'Security',
    changePassword: 'Change password',
    twoFactor: 'Two-factor verification (2FA)',
    recoveryEmail: 'Recovery email',
    privacy: 'Privacy',
    privateAccount: 'Private account',
    hideActivity: 'Hide my activity',
    whoMention: 'Who can mention me',
    all: 'Everyone',
    onlyFollowers: 'Only Followers',
    nobody: 'Nobody',
    nightMode: 'Dark Mode',
    accessibility: 'Accessibility & Interface',
    highContrast: 'Increase color contrast',
    textSize: 'Global text size',
    small: 'small',
    medium: 'medium',
    large: 'large',
    systemLanguage: 'System language',
    logout: 'logout',
  },
  'Español': {
    home: 'Inicio',
    search: 'Buscar',
    profile: 'Mi Perfil',
    settings: 'Configuración',
    feedTitle: 'INICIO',
    whatThinking: '¿En qué estás pensando?',
    publish: 'Publicar',
    comments: 'comentarios',
    reposts: 'reposts',
    likes: 'me gusta',
    noPosts: 'No hay publicaciones por aquí todavía.',
    noComments: 'Sin comentarios aún. ¡Sé el primero!',
    commentPlaceholder: 'Escribe un comentario...',
    commentBtn: 'Comentar',
    loading: 'Cargando...',
    searchTitle: 'BUSCAR',
    muralTitle: 'Muro Académico',
    noAnnouncements: 'No se encontraron avisos.',
    createAnnouncement: 'Crear Aviso',
    editProfile: 'Editar Perfil',
    followers: 'seguidores',
    following: 'siguiendo',
    teacher: '🎓 Docente',
    student: '📖 Estudiante',
    postsTab: 'Publicaciones',
    repostsTab: 'Reposts',
    follow: 'Seguir',
    unfollow: 'Siguiendo',
    messagesTitle: 'MENSAJES',
    searchContacts: 'Buscar contactos...',
    contactsAvailable: 'CONTACTOS DISPONIBLES',
    noContacts: 'No se encontraron contactos.',
    connected: 'Conectado',
    chatPlaceholder: 'Chatear con',
    voiceMsg: 'Mensaje de voz',
    calling: 'Llamando...',
    callConnected: 'Conectado',
    callProtected: 'Llamada Protegida',
    callEncrypted: 'Encriptada de extremo a extremo',
    micMute: 'Silenciar Micrófono',
    micUnmute: 'Activar Micrófono',
    camMute: 'Desactivar Cámara',
    camUnmute: 'Activar Cámara',
    endCall: 'Terminar Llamada',
    settingsTitle: 'CONFIGURACIÓN',
    security: 'Seguridad',
    changePassword: 'Cambiar contraseña',
    twoFactor: 'Verificación en dos pasos (2FA)',
    recoveryEmail: 'Correo de recuperación',
    privacy: 'Privacidad',
    privateAccount: 'Cuenta privada',
    hideActivity: 'Ocultar mi actividad',
    whoMention: 'Quién puede mencionarme',
    all: 'Todos',
    onlyFollowers: 'Solo Seguidores',
    nobody: 'Nadie',
    nightMode: 'Modo Oscuro',
    accessibility: 'Accesibilidad e Interfaz',
    highContrast: 'Aumentar contraste de colores',
    textSize: 'Tamaño de texto global',
    small: 'pequeño',
    medium: 'mediano',
    large: 'grande',
    systemLanguage: 'Idioma del sistema',
    logout: 'cerrar sesión',
  },
  'Français': {
    home: 'Accueil',
    search: 'Rechercher',
    profile: 'Mon Profil',
    settings: 'Paramètres',
    feedTitle: 'ACCUEIL',
    whatThinking: 'À quoi pensez-vous?',
    publish: 'Publier',
    comments: 'commentaires',
    reposts: 'reposts',
    likes: 'mentions j’aime',
    noPosts: 'Aucune publication ici pour le moment.',
    noComments: 'Aucun commentaire pour le moment. Soyez le premier!',
    commentPlaceholder: 'Écrire un commentaire...',
    commentBtn: 'Commenter',
    loading: 'Chargement...',
    searchTitle: 'RECHERCHE',
    muralTitle: 'Mur Académique',
    noAnnouncements: 'Aucune annonce trouvée.',
    createAnnouncement: 'Créer une annonce',
    editProfile: 'Modifier le profil',
    followers: 'abonnés',
    following: 'abonnements',
    teacher: '🎓 Enseignant',
    student: '📖 Étudiant',
    postsTab: 'Publications',
    repostsTab: 'Reposts',
    follow: 'Suivre',
    unfollow: 'Abonné',
    messagesTitle: 'MESSAGES',
    searchContacts: 'Rechercher des contacts...',
    contactsAvailable: 'CONTACTS DISPONIBLES',
    noContacts: 'Aucun contact trouvé.',
    connected: 'En ligne',
    chatPlaceholder: 'Discuter avec',
    voiceMsg: 'Message vocal',
    calling: 'Appel en cours...',
    callConnected: 'Connecté',
    callProtected: 'Appel Sécurisé',
    callEncrypted: 'Chiffré de bout en bout',
    micMute: 'Couper le micro',
    micUnmute: 'Activer le micro',
    camMute: 'Désactiver la caméra',
    camUnmute: 'Activer la caméra',
    endCall: 'Raccrocher',
    settingsTitle: 'PARAMÈTRES',
    security: 'Sécurité',
    changePassword: 'Modifier le mot de passe',
    twoFactor: 'Validation en deux étapes (2FA)',
    recoveryEmail: 'E-mail de récupération',
    privacy: 'Confidentialité',
    privateAccount: 'Compte privé',
    hideActivity: 'Masquer mon activité',
    whoMention: 'Qui peut me mentionner',
    all: 'Tout le monde',
    onlyFollowers: 'Seulement les abonnés',
    nobody: 'Personne',
    nightMode: 'Mode Sombre',
    accessibility: 'Accessibilité & Interface',
    highContrast: 'Augmenter le contraste',
    textSize: 'Taille du texte global',
    small: 'petite',
    medium: 'moyenne',
    large: 'grande',
    systemLanguage: 'Langue du système',
    logout: 'se déconnecter',
  },
  'Deutsch': {
    home: 'Startseite',
    search: 'Suche',
    profile: 'Mein Profil',
    settings: 'Einstellungen',
    feedTitle: 'STARTSEITE',
    whatThinking: 'Was geht dir durch den Kopf?',
    publish: 'Veröffentlichen',
    comments: 'Kommentare',
    reposts: 'Reposts',
    likes: 'Gefällt mir',
    noPosts: 'Hier gibt es noch keine Beiträge.',
    noComments: 'Noch keine Kommentare. Schreibe den ersten!',
    commentPlaceholder: 'Einen Kommentar schreiben...',
    commentBtn: 'Kommentieren',
    loading: 'Laden...',
    searchTitle: 'SUCHE',
    muralTitle: 'Akademische Pinnwand',
    noAnnouncements: 'Keine Ankündigungen gefunden.',
    createAnnouncement: 'Ankündigung erstellen',
    editProfile: 'Profil bearbeiten',
    followers: 'Follower',
    following: 'Gefolgt',
    teacher: '🎓 Lehrkraft',
    student: '📖 Student',
    postsTab: 'Beiträge',
    repostsTab: 'Reposts',
    follow: 'Folgen',
    unfollow: 'Gefolgt',
    messagesTitle: 'NACHRICHTEN',
    searchContacts: 'Kontakte suchen...',
    contactsAvailable: 'VERFÜGBARE KONTAKTE',
    noContacts: 'Keine Kontakte gefunden.',
    connected: 'Online',
    chatPlaceholder: 'Chatten mit',
    voiceMsg: 'Sprachnachricht',
    calling: 'Anrufen...',
    callConnected: 'Verbunden',
    callProtected: 'Gesichertes Telefonat',
    callEncrypted: 'Ende-zu-Ende verschlüsselt',
    micMute: 'Stummschalten',
    micUnmute: 'Mikrofon aktivieren',
    camMute: 'Kamera ausschalten',
    camUnmute: 'Kamera einschalten',
    endCall: 'Auflegen',
    settingsTitle: 'EINSTELLUNGEN',
    security: 'Sicherheit',
    changePassword: 'Passwort ändern',
    twoFactor: 'Zwei-Faktor-Authentifizierung (2FA)',
    recoveryEmail: 'Wiederherstellungs-E-Mail',
    privacy: 'Privatsphäre',
    privateAccount: 'Privates Konto',
    hideActivity: 'Aktivitätsstatus verbergen',
    whoMention: 'Wer kann mich erwähnen',
    all: 'Jeder',
    onlyFollowers: 'Nur Follower',
    nobody: 'Niemand',
    nightMode: 'Dunkelmodus',
    accessibility: 'Barrierefreiheit & Interface',
    highContrast: 'Farbkontrast erhöhen',
    textSize: 'Globale Textgröße',
    small: 'klein',
    medium: 'mittel',
    large: 'groß',
    systemLanguage: 'Systemsprache',
    logout: 'abmelden',
  },
  'Italiano': {
    home: 'Home',
    search: 'Cerca',
    profile: 'Il Mio Profilo',
    settings: 'Impostazioni',
    feedTitle: 'HOME',
    whatThinking: 'A cosa stai pensando?',
    publish: 'Pubblica',
    comments: 'commenti',
    reposts: 'repost',
    likes: 'mi piace',
    noPosts: 'Non ci sono ancora post qui.',
    noComments: 'Ancora nessun commento. Scrivi il primo!',
    commentPlaceholder: 'Scrivi un commento...',
    commentBtn: 'Commenta',
    loading: 'Caricamento...',
    searchTitle: 'CERCA',
    muralTitle: 'Bacheca Accademica',
    noAnnouncements: 'Nessun annuncio trovato.',
    createAnnouncement: 'Crea Annuncio',
    editProfile: 'Modifica Profilo',
    followers: 'follower',
    following: 'seguiti',
    teacher: '🎓 Docente',
    student: '📖 Studente',
    postsTab: 'Post',
    repostsTab: 'Repost',
    follow: 'Segui',
    unfollow: 'Segui già',
    messagesTitle: 'MESSAGGI',
    searchContacts: 'Cerca contatti...',
    contactsAvailable: 'CONTATTI DISPONIBILI',
    noContacts: 'Nessun contatto trovato.',
    connected: 'Connesso',
    chatPlaceholder: 'Chatta con',
    voiceMsg: 'Messaggio vocale',
    calling: 'Chiamata in corso...',
    callConnected: 'Connesso',
    callProtected: 'Chiamata Protetta',
    callEncrypted: 'Crittografato end-to-end',
    micMute: 'Disattiva microfono',
    micUnmute: 'Attiva microfono',
    camMute: 'Disattiva fotocamera',
    camUnmute: 'Attiva fotocamera',
    endCall: 'Termina Chiamata',
    settingsTitle: 'IMPOSTAZIONI',
    security: 'Sicurezza',
    changePassword: 'Cambia password',
    twoFactor: 'Verifica in due passaggi (2FA)',
    recoveryEmail: 'E-mail di recupero',
    privacy: 'Privacy',
    privateAccount: 'Account privato',
    hideActivity: 'Nascondi la mia attività',
    whoMention: 'Chi può menzionarmi',
    all: 'Tutti',
    onlyFollowers: 'Solo Follower',
    nobody: 'Nessuno',
    nightMode: 'Modalità Scura',
    accessibility: 'Accessibilità e Interfaccia',
    highContrast: 'Aumenta contrasto colori',
    textSize: 'Dimensione testo globale',
    small: 'piccolo',
    medium: 'medio',
    large: 'grande',
    systemLanguage: 'Lingua del sistema',
    logout: 'disconnettiti',
  },
  '日本語': {
    home: 'ホーム',
    search: '検索',
    profile: 'プロフィール',
    settings: '設定',
    feedTitle: 'ホーム',
    whatThinking: '今何してる？',
    publish: '投稿する',
    comments: '件のコメント',
    reposts: '件のリポスト',
    likes: '件のいいね',
    noPosts: 'まだ投稿はありません。',
    noComments: 'コメントはまだありません。最初のコメントを書きましょう！',
    commentPlaceholder: 'コメントを書く...',
    commentBtn: '送信',
    loading: '読み込み中...',
    searchTitle: '検索',
    muralTitle: '学術掲示板',
    noAnnouncements: 'お知らせはありません。',
    createAnnouncement: 'お知らせ作成',
    editProfile: 'プロフィール編集',
    followers: 'フォロワー',
    following: 'フォロー中',
    teacher: '🎓 教員',
    student: '📖 学生',
    postsTab: '投稿',
    repostsTab: 'リポスト',
    follow: 'フォローする',
    unfollow: 'フォロー中',
    messagesTitle: 'メッセージ',
    searchContacts: '連絡先を検索...',
    contactsAvailable: '連絡可能リスト',
    noContacts: '連絡先が見つかりません。',
    connected: '接続中',
    chatPlaceholder: 'チャットする',
    voiceMsg: 'ボイスメッセージ',
    calling: '発信中...',
    callConnected: '通話中',
    callProtected: '保護された通話',
    callEncrypted: 'エンドツーエンドで暗号化',
    micMute: 'マイク消音',
    micUnmute: 'マイクオン',
    camMute: 'カメラオフ',
    camUnmute: 'カメラオン',
    endCall: '通話を終了',
    settingsTitle: '設定',
    security: 'セキュリティ',
    changePassword: 'パスワード変更',
    twoFactor: '二要素認証 (2FA)',
    recoveryEmail: '復旧用メールアドレス',
    privacy: 'プライバシー',
    privateAccount: '非公開アカウント',
    hideActivity: 'アクティビティステータス非表示',
    whoMention: '自分をメンションできる人',
    all: '全員',
    onlyFollowers: 'フォロワーのみ',
    nobody: '許可しない',
    nightMode: 'ダークモード',
    accessibility: 'アクセシビリティとUI設定',
    highContrast: 'ハイコントラストモード',
    textSize: '全体の文字サイズ',
    small: '小',
    medium: '中',
    large: '大',
    systemLanguage: 'システム言語',
    logout: 'ログアウト',
  },
  '中文': {
    home: '首页',
    search: '搜索',
    profile: '个人主页',
    settings: '设置',
    feedTitle: '首页',
    whatThinking: '分享你的新鲜事...',
    publish: '发布',
    comments: '条评论',
    reposts: '次转发',
    likes: '次赞',
    noPosts: '目前还没有动态。',
    noComments: '暂无评论。来发表第一条评论吧！',
    commentPlaceholder: '写下你的评论...',
    commentBtn: '评论',
    loading: '加载中...',
    searchTitle: '搜索',
    muralTitle: '学术公告栏',
    noAnnouncements: '未找到公告。',
    createAnnouncement: '发布公告',
    editProfile: '编辑个人资料',
    followers: '粉丝',
    following: '关注',
    teacher: '🎓 教师',
    student: '📖 学生',
    postsTab: '动态',
    repostsTab: '转发',
    follow: '关注',
    unfollow: '已关注',
    messagesTitle: '消息',
    searchContacts: '搜索联系人...',
    contactsAvailable: '联系人列表',
    noContacts: '未找到联系人。',
    connected: '在线',
    chatPlaceholder: '聊天人：',
    voiceMsg: '语音消息',
    calling: '呼叫中...',
    callConnected: '已接通',
    callProtected: '安全通话',
    callEncrypted: '端到端加密',
    micMute: '静音',
    micUnmute: '取消静音',
    camMute: '关闭摄像头',
    camUnmute: '开启摄像头',
    endCall: '挂断',
    settingsTitle: '设置',
    security: '安全',
    changePassword: '修改密码',
    twoFactor: '双重身份验证 (2FA)',
    recoveryEmail: '密保邮箱',
    privacy: '隐私',
    privateAccount: '私密账户',
    hideActivity: '隐藏活动状态',
    whoMention: '谁可以提及我',
    all: '所有人',
    onlyFollowers: '仅关注我的人',
    nobody: '无人',
    nightMode: '夜间模式',
    accessibility: '无障碍与界面',
    highContrast: '高对比度',
    textSize: '全局文字大小',
    small: '小',
    medium: '中',
    large: '大',
    systemLanguage: '系统语言',
    logout: '退出登录',
  },
  'Русский': {
    home: 'Главная',
    search: 'Поиск',
    profile: 'Мой Профиль',
    settings: 'Настройки',
    feedTitle: 'ГЛАВНАЯ',
    whatThinking: 'Что у вас нового?',
    publish: 'Опубликовать',
    comments: 'коммент.',
    reposts: 'репостов',
    likes: 'лайков',
    noPosts: 'Здесь пока нет публикаций.',
    noComments: 'Комментариев пока нет. Будьте первым!',
    commentPlaceholder: 'Написать комментарий...',
    commentBtn: 'Комментировать',
    loading: 'Загрузка...',
    searchTitle: 'ПОИСК',
    muralTitle: 'Академическая доска',
    noAnnouncements: 'Объявлений не найдено.',
    createAnnouncement: 'Создать объявление',
    editProfile: 'Редактировать профиль',
    followers: 'подписчиков',
    following: 'подписок',
    teacher: '🎓 Преподаватель',
    student: '📖 Студент',
    postsTab: 'Публикации',
    repostsTab: 'Репосты',
    follow: 'Подписаться',
    unfollow: 'Вы подписаны',
    messagesTitle: 'СООБЩЕНИЯ',
    searchContacts: 'Поиск контактов...',
    contactsAvailable: 'ДОСТУПНЫЕ КОНТАКТЫ',
    noContacts: 'Контакты не найдены.',
    connected: 'В сети',
    chatPlaceholder: 'Чат с',
    voiceMsg: 'Голосовое сообщение',
    calling: 'Звонок...',
    callConnected: 'Соединено',
    callProtected: 'Защищенный звонок',
    callEncrypted: 'Сквозное шифрование',
    micMute: 'Выключить микрофон',
    micUnmute: 'Включить микрофон',
    camMute: 'Выключить камеру',
    camUnmute: 'Включить камеру',
    endCall: 'Завершить звонок',
    settingsTitle: 'НАСТРОЙКИ',
    security: 'Безопасность',
    changePassword: 'Сменить пароль',
    twoFactor: 'Двухфакторная аутентификация (2FA)',
    recoveryEmail: 'Резервный e-mail',
    privacy: 'Конфиденциальность',
    privateAccount: 'Закрытый аккаунт',
    hideActivity: 'Скрыть мою активность',
    whoMention: 'Кто может упоминать меня',
    all: 'Все',
    onlyFollowers: 'Только подписчики',
    nobody: 'Никто',
    nightMode: 'Темная тема',
    accessibility: 'Доступность и Интерфейс',
    highContrast: 'Увеличить контрастность',
    textSize: 'Размер текста',
    small: 'мелкий',
    medium: 'средний',
    large: 'крупный',
    systemLanguage: 'Язык системы',
    logout: 'выйти из аккаунта',
  },
  'العربية': {
    home: 'الرئيسية',
    search: 'بحث',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    feedTitle: 'الرئيسية',
    whatThinking: 'بمَ تفكر؟',
    publish: 'نشر',
    comments: 'تعليقات',
    reposts: 'إعادات نشر',
    likes: 'إعجابات',
    noPosts: 'لا توجد منشورات هنا بعد.',
    noComments: 'لا توجد تعليقات بعد. كن أول من يعلق!',
    commentPlaceholder: 'اكتب تعليقًا...',
    commentBtn: 'تعليق',
    loading: 'جاري التحميل...',
    searchTitle: 'بحث',
    muralTitle: 'المجلس الأكاديمي',
    noAnnouncements: 'لم يتم العثور على إعلانات.',
    createAnnouncement: 'إنشاء إعلان',
    editProfile: 'تعديل الملف الشخصي',
    followers: 'متابعون',
    following: 'متابعة',
    teacher: '🎓 أستاذ',
    student: '📖 طالب',
    postsTab: 'المنشورات',
    repostsTab: 'إعادات النشر',
    follow: 'متابعة',
    unfollow: 'متابع',
    messagesTitle: 'الرسائل',
    searchContacts: 'البحث عن جهات اتصال...',
    contactsAvailable: 'جهات الاتصال المتاحة',
    noContacts: 'لم يتم العثور على جهات اتصال.',
    connected: 'نشط الآن',
    chatPlaceholder: 'دردشة مع',
    voiceMsg: 'رسالة صوتية',
    calling: 'جاري الاتصال...',
    callConnected: 'تم الاتصال',
    callProtected: 'مكالمة آمنة',
    callEncrypted: 'مشفرة من الطرفين',
    micMute: 'كتم الميكروفون',
    micUnmute: 'تفعيل الميكروفون',
    camMute: 'إيقاف الكاميرا',
    camUnmute: 'تشغيل الكاميرا',
    endCall: 'إنهاء المكالمة',
    settingsTitle: 'الإعدادات',
    security: 'الأمان',
    changePassword: 'تغيير كلمة المرور',
    twoFactor: 'التحقق بخطوتين (2FA)',
    recoveryEmail: 'بريد الاسترداد',
    privacy: 'الخصوصية',
    privateAccount: 'حساب خاص',
    hideActivity: 'إخفاء حالة النشاط',
    whoMention: 'من يمكنه الإشارة إلي',
    all: 'الجميع',
    onlyFollowers: 'المتابعون فقط',
    nobody: 'لا أحد',
    nightMode: 'الوضع الداكن',
    accessibility: 'سهولة الوصول والواجهة',
    highContrast: 'زيادة تباين الألوان',
    textSize: 'حجم النص العام',
    small: 'صغير',
    medium: 'متوسط',
    large: 'كبير',
    systemLanguage: 'لغة النظام',
    logout: 'تسجيل الخروج',
  },
  'हिन्दी': {
    home: 'होम',
    search: 'खोजें',
    profile: 'मेरी प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    feedTitle: 'होम',
    whatThinking: 'आपके मन में क्या है?',
    publish: 'प्रकाशित करें',
    comments: 'टिप्पणियाँ',
    reposts: 'रीपोस्ट',
    likes: 'पसंद',
    noPosts: 'यहाँ अभी तक कोई पोस्ट नहीं है।',
    noComments: 'कोई टिप्पणी नहीं। पहली टिप्पणी करें!',
    commentPlaceholder: 'एक टिप्पणी लिखें...',
    commentBtn: 'टिप्पणी करें',
    loading: 'लोड हो रहा है...',
    searchTitle: 'खोजें',
    muralTitle: 'शैक्षणिक सूचना बोर्ड',
    noAnnouncements: 'कोई सूचना नहीं मिली।',
    createAnnouncement: 'सूचना बनाएं',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    followers: 'फ़ॉलोअर्स',
    following: 'फ़ॉলো कर रहे हैं',
    teacher: '🎓 शिक्षक',
    student: '📖 छात्र',
    postsTab: 'पोस्ट',
    repostsTab: 'रीपोस्ट',
    follow: 'फ़ॉलो करें',
    unfollow: 'फ़ॉলো कर रहे हैं',
    messagesTitle: 'संदेश',
    searchContacts: 'संपर्क खोजें...',
    contactsAvailable: 'उपलब्ध संपर्क',
    noContacts: 'कोई संपर्क नहीं मिला।',
    connected: 'ऑनलाइन',
    chatPlaceholder: 'बातचीत करें',
    voiceMsg: 'वॉयस संदेश',
    calling: 'कॉल हो रही है...',
    callConnected: 'कनेक्टेड',
    callProtected: 'सुरक्षित कॉल',
    callEncrypted: 'एंड-टू-एंड एन्क्रिप्टेड',
    micMute: 'म्यूट करें',
    micUnmute: 'अनम्यूट करें',
    camMute: 'कैमरा बंद करें',
    camUnmute: 'कैमरा चालू करें',
    endCall: 'कॉल समाप्त करें',
    settingsTitle: 'सेटिंग्स',
    security: 'सुरक्षा',
    changePassword: 'पासवर्ड बदलें',
    twoFactor: 'टू-फैक्टर प्रमाणीकरण (2FA)',
    recoveryEmail: 'रिकवरी ईमेल',
    privacy: 'गोपनीयता',
    privateAccount: 'निजी खाता',
    hideActivity: 'सक्रियता छुपाएं',
    whoMention: 'कौन मुझे मेंशन कर सकता है',
    all: 'सभी',
    onlyFollowers: 'केवल फ़ॉलोअर्स',
    nobody: 'कोई नहीं',
    nightMode: 'डार्क मोड',
    accessibility: 'एक्सेसिबिलिटी और इंटरफ़ेस',
    highContrast: 'रंग कंट्रास्ट बढ़ाएं',
    textSize: 'टेक्स्ट का आकार',
    small: 'छोटा',
    medium: 'मध्यम',
    large: 'बड़ा',
    systemLanguage: 'सिस्टम की भाषा',
    logout: 'लॉगआउट करें',
  },
  '한국어': {
    home: '홈',
    search: '검색',
    profile: '프로필',
    settings: '설정',
    feedTitle: '홈',
    whatThinking: '무슨 생각을 하고 계신가요?',
    publish: '게시',
    comments: '개의 댓글',
    reposts: '개의 리포스트',
    likes: '개의 좋아요',
    noPosts: '아직 게시물이 없습니다.',
    noComments: '댓글이 없습니다. 첫 댓글을 작성해보세요!',
    commentPlaceholder: '댓글 작성...',
    commentBtn: '게시',
    loading: '로딩 중...',
    searchTitle: '검색',
    muralTitle: '학술 게시판',
    noAnnouncements: '공지사항이 없습니다.',
    createAnnouncement: '공지 생성',
    editProfile: '프로필 편집',
    followers: '팔로워',
    following: '팔로잉',
    teacher: '🎓 교원',
    student: '📖 학생',
    postsTab: '게시물',
    repostsTab: '리포스트',
    follow: '팔로우',
    unfollow: '팔로잉 중',
    messagesTitle: '메시지',
    searchContacts: '연락처 검색...',
    contactsAvailable: '연락 가능 목록',
    noContacts: '연락처를 찾을 수 없습니다.',
    connected: '온라인',
    chatPlaceholder: '대화 상대:',
    voiceMsg: '음성 메시지',
    calling: '통화 연결 중...',
    callConnected: '연결됨',
    callProtected: '보안 통화',
    callEncrypted: '종단간 암호화됨',
    micMute: '음소거',
    micUnmute: '마이크 켜기',
    camMute: '카메라 끄기',
    camUnmute: '카메라 켜기',
    endCall: '통화 종료',
    settingsTitle: '설정',
    security: '보안',
    changePassword: '비밀번호 변경',
    twoFactor: '2단계 인증 (2FA)',
    recoveryEmail: '복구 이메일',
    privacy: '개인정보 보호',
    privateAccount: '비공개 계정',
    hideActivity: '활동 상태 숨기기',
    whoMention: '나를 멘션할 수 있는 사람',
    all: '모두',
    onlyFollowers: '팔로워만',
    nobody: '허용 안 함',
    nightMode: '다크 모드',
    accessibility: '접근성 및 인터페이스',
    highContrast: '색상 대비 증가',
    textSize: '글자 크기',
    small: '작게',
    medium: '보통',
    large: '크게',
    systemLanguage: '시스템 언어',
    logout: '로그아웃',
  }
};

export function useLanguage() {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('educonnect-lang') || 'Português (BR)';
  });

  useEffect(() => {
    const handleLanguageChange = () => {
      setLang(localStorage.getItem('educonnect-lang') || 'Português (BR)');
    };

    window.addEventListener('educonnect-language-change', handleLanguageChange);
    return () => {
      window.removeEventListener('educonnect-language-change', handleLanguageChange);
    };
  }, []);

  const translate = (key) => {
    const langDict = translations[lang] || translations['Português (BR)'];
    return langDict[key] || key;
  };

  return { lang, translate };
}
